receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default/
    headers:
      Authorization: "${OPENOBSERVE_AUTH_HEADER}"
      organization: default
      stream-name: default
    tls:
      insecure: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 256

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]
