apiVersion: batch/v1
kind: Job
metadata:
  name: rag-pipe-liquibase-migrations
  namespace: rag-pipe
spec:
  template:
    metadata:
      name: rag-pipe-liquibase-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: liquibase-migration
          image: liquibase/liquibase:4.27.0
          command:
            - /liquibase/liquibase
            - --changelog-file=db.changelog-master.yaml
            - --url=$(DATABASE_JDBC_URL)
            - --username=$(POSTGRES_USER)
            - --password=$(POSTGRES_PASSWORD)
            - --driver=org.postgresql.Driver
            - update
          env:
            - name: DATABASE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: rag-pipe-secrets
                  key: DATABASE_JDBC_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: rag-pipe-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rag-pipe-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: migration-vol
              mountPath: /liquibase/changelog
      volumes:
        - name: migration-vol
          configMap:
            name: rag-pipe-liquibase-changelogs
